{{- if .Values.plugins.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mosaikit.fullname" . }}-plugins
  labels:
    {{- include "mosaikit.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.plugins.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.plugins.persistence.size }}
{{- end }}
